name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches:
      - muratsat-patch-1
  workflow_dispatch:

env:
  REGISTRY: ecapmsl.azurecr.io
  IMAGE_NAME: ecapmsl.azurecr.io/ecapmsl-docker:latest

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: log in to azure and push the build
        run: |
        docker login $REGISTRY --username ecapmsl --password weMrlZpCb9VNSeJU=oEKvwlkTg9a8Esi
        docker build -t $IMAGE_NAME . 
        docker push $IMAGE_NAME

    