name: Docker build and deploy

on:
  push:
    branches:
      - muratsat-patch-1
  workflow_dispatch:

env:
  REGISTRY: ecapmsl.azurecr.io
  IMAGE_NAME: ecapmsl.azurecr.io/ecapmsl-docker:latest
  APP_NAME: ecapmsl-docker

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: login to azure container
        uses: azure/docker-login@v1
        with:
          login-server: $REGISTRY
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      
      - name: build and push
        run: |
          docker login $REGISTRY --username ${{ secrets.REGISTRY_USERNAME }} --password ${{ secrets.REGISTRY_PASSWORD }}
          docker build . -t $IMAGE_NAME
          docker push $IMAGE_NAME

      - name: deploy to azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: $APP_NAME
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: $IMAGE_NAME
